export type FbGraphApiResponseHeaders = {
    etag?: string;
    'content-type'?: string;
    vary?: string;
    'cross-origin-resource-policy'?: string;
    'x-app-usage'?: string;
    'access-control-allow-origin'?: string;
    'facebook-api-version'?: string;
    'strict-transport-security'?: string;
    pragma?: string;
    'cache-control'?: string;
    expires?: string;
    'x-fb-request-id'?: string;
    'x-fb-trace-id'?: string;
    'x-fb-rev'?: string;
    'x-fb-debug'?: string;
    'content-length'?: string;
    date?: string;
    'x-fb-connection-quality'?: string;
    'alt-svc'?: string;
};
